post_install() {
    # Enable TinyDM for automatic login and Catacomb start.
    systemctl enable tinydm
    if ! [ -L /var/lib/tinydm/default-session.desktop ]; then
      if [ -f "/usr/share/wayland-sessions/catacomb.desktop" ]; then
        tinydm-set-session -s "/usr/share/wayland-sessions/catacomb.desktop"
      fi
    fi
}

post_upgrade() {
    post_install
}

post_remove() {
  tinydm-unset-session "/usr/share/wayland-sessions/catacomb.desktop"
  systemctl disable tinydm
}
