monitor.alsa.rules = [{
    # Matches the FP5's built-in output sinks.
    matches = [{
        node.name = "~alsa_output.*"
        alsa.card_name = "Fairphone 5"
    }]
    actions = {
        update-props = {
            audio.format = "S32LE"
        }
    }
}]
